title: Makeself
description: A self-extracting archiving tool for Unix systems, in 100% shell script.
google_analytics: UA-1803317-14
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
  - jekyll-seo-tag
