name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout Makeself
      uses: actions/checkout@v2

    - name: Build release
      run: |
        git submodule update --init --recursive
        make

    - name: Run tests
      run: make test
