name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Install Linux packages
      if: runner.os == 'Linux'
      run: sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y install pbzip2

    - name: Install macOS packages
      if: runner.os == 'macOS'
      run: brew install pbzip2 md5sha1sum

    - name: Checkout Makeself
      uses: actions/checkout@v2

    - name: Build release
      run: |
        git submodule update --init --recursive
        make

    - name: Run tests
      run: make test
