name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Install Linux packages
      if: runner.os == 'Linux'
      run: sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y install pbzip2 zstd

    - name: Install macOS packages
      if: runner.os == 'macOS'
      run: brew install pbzip2 coreutils zstd

    - name: Checkout Makeself
      uses: actions/checkout@v2

    - name: Build release
      run: |
        git submodule update --init --recursive
        make

    - name: Upload build artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v1
      with:
        name: Makeself-Build
        path: release
        
    - name: Run tests
      run: make test

  test-freebsd:
    needs: test
    runs-on: macos-latest
    name: Test Makeself on FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: Test on FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        usesh: true
        prepare: pkg install -y pbzip2 git 
        run: |
          pwd; freebsd-version
          git submodule update --init --recursive
          make && make test

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Makeself
      uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: megastep/shell-linter@develop
      with:
        path: "makeself.sh"
        severity: "error"
